# Generated by Django 5.1.2 on 2024-10-15 18:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customer',
            options={},
        ),
        migrations.AlterModelTable(
            name='customer',
            table='Customer',
        ),
    ]
